[package]
name = "eggstraction"
version = "0.1.0"
edition = "2024"

[dependencies]
egg = { version = "0.10.0", features = ["lp"] }
ordered-float = "5.0.0"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"